name: Build APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build with Buildozer
        uses: kivy/buildozer-action@master
        with:
          buildozer_version: master
          workdir: .
        env:
          # Đảm bảo Buildozer không bị treo ở bước accept license
          ANDROIDSDK_ACCEPT_LICENSES: 1

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: bin/*.apk
