name: Build APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4  # Đã cập nhật lên v4

    - name: Build with Buildozer
      uses: ArtemSBulgakov/buildozer-action@v1
      id: buildozer
      with:
        buildozer_version: latest

    - name: Upload artifacts
      uses: actions/upload-artifact@v4 # Đã cập nhật lên v4 để sửa lỗi
      with:
        name: package
        path: ${{ steps.buildozer.outputs.filename }}
